name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Jekyll Site
      uses: actions/jekyll-build-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Build Status File
      run: echo "Build succeeded $(date)" > _site/build-status.txt

    - name: Upload Site to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site
