name: Run Workflow on Page Update

on:
  push:
    paths:
      - 'index.html'

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run your custom action
        run: echo "Workflow triggered by an update to index.html"
