name: Manually Triggered Workflow

on:
  workflow_dispatch:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run custom action
        run: echo "Workflow manually triggered via API"
